---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- name: altas de Programas Producto antes de IPL de OS Linux
  block:
    - name: alta de Programas Producto
      shell: if [ -f {{ gdmfsasb }}patrol.asb ]; then echo alta; fi
      register: alta_patrol

    - include_tasks: altas_ppaps/alta_patrol.yml
      when: alta_patrol.stdout == "alta"

    - shell: if [ -f {{ gdmfsasb }}capacity.asb ]; then echo alta; fi
      register: alta_capacity

    - include_tasks: altas_ppaps/alta_capacity.yml
      when: alta_capacity.stdout == "alta"

    - shell: if [ -f {{ gdmfsasb }}ctm.asb ]; then echo alta; fi
      register: alta_controlm

    - include_tasks: altas_ppaps/alta_controlm.yml
      when: alta_controlm.stdout == "alta"

    - shell: if [ -f {{ gdmfsasb }}dim.asb ]; then echo alta; fi
      register: alta_dimensions

    - include_tasks: altas_ppaps/alta_dimensions.yml
      when: alta_dimensions.stdout == "alta"

    - shell: if [ -f {{ gdmfsasb }}cd.asb ]; then echo alta; fi
      register: alta_connectdirect

    - include_tasks: altas_ppaps/alta_connectdirect.yml
      when: alta_connectdirect.stdout == "alta"

#    - shell: if [ -f {{ gdmfsasb }}s1.asb ]; then echo alta; fi
#      register: alta_s1

#    - include_tasks: altas_ppaps/alta_sentinelone.yml
#      when: alta_s1.stdout == "alta"

- name: altas de Aplicaciones antes de IPL de OS Linux
  block:
    - name: alta Aplicaciones
      shell: if [ -f {{ gdmfsasb }}httpserver80s.asb ]; then echo alta; fi
      register: alta_http80s

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver80s.asb)
        do
          $https stop
        done
      when: alta_http80s.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}httpserver80d.asb ]; then echo alta; fi
      register: alta_http80d

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver80d.asb)
        do
          $https stop
        done
      when: alta_http80d.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}httpserver85d.asb ]; then echo alta; fi
      register: alta_http85s

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver85s.asb)
        do
          $https stop
        done
      become: true
      become_user: was60
      become_method: su
      become_exe: sudo su -
      when: alta_http85s.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}httpserver85d.asb ]; then echo alta; fi
      register: alta_http85d

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver85d.asb)
        do
          $https stop
        done
      become: true
      become_user: was60
      become_method: su
      become_exe: sudo su -
      when: alta_http85d.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}httpserver90d.asb ]; then echo alta; fi
      register: alta_http90s

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver90s.asb)
        do
          $https stop
        done
      become: true
      become_user: was60
      become_method: su
      become_exe: sudo su -
      when: alta_http90s.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}httpserver90d.asb ]; then echo alta; fi
      register: alta_http90d

    - shell: |
        for https in $(cat {{ gdmfsasb }}httpserver90d.asb)
        do
          $https stop
        done
      become: true
      become_user: was60
      become_method: su
      become_exe: sudo su -
      when: alta_http90d.stdout == "alta"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}websphere80.asb ]; then echo "/WebSphere80/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere
      become: yes
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere80' in wasversion.stdout"
      ignore_errors: true


    - shell: if [ -f {{ gdmfsasb }}websphere85.asb ]; then echo "/WebSphere85/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere
      become: yes
      become_user: was60
      become_method: su
      become_exe: sudo su -
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere85' in wasversion.stdout"
      ignore_errors: true

    - shell: if [ -f {{ gdmfsasb }}websphere90.asb ]; then echo "/WebSphere90/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere
      become: yes
      become_user: was60
      become_method: su
      become_exe: sudo su -
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere90' in wasversion.stdout"
      ignore_errors: true
#----
    - name: alta MQ
      shell: if [ -f {{ gdmfsasb }}mqm.asb ]; then echo alta; fi
      register: alta_mqm

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmfsasb }}mqm.asb)
        do
        $(cat {{ gdmfsasb }}mqma.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm.stdout"
      ignore_errors: true

    - name: alta MQ8
      shell: if [ -f {{ gdmfsasb }}mqm8.asb ]; then echo alta; fi
      register: alta_mqm8

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmfsasb }}mqm8.asb)
        do
        $(cat {{ gdmfsasb }}mqm8a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm8.stdout"
      ignore_errors: true

    - name: alta MQ9
      shell: if [ -f {{ gdmfsasb }}mqm9.asb ]; then echo alta; fi
      register: alta_mqm9

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmfsasb }}mqm9.asb)
        do
        $(cat {{ gdmfsasb }}mqm9a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm9.stdout"
      ignore_errors: true

    - name: alta MQ90
      shell: if [ -f {{ gdmfsasb }}mqm90.asb ]; then echo alta; fi
      register: alta_mqm90

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmfsasb }}mqm90.asb)
        do
        $(cat {{ gdmfsasb }}mqm90a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm90.stdout"
      ignore_errors: true

    - name: alta MQ93
      shell: if [ -f {{ gdmfsasb }}mqm93.asb ]; then echo alta; fi
      register: alta_mqm93

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmfsasb }}mqm93.asb)
        do
        $(cat {{ gdmfsasb }}mqm93a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm93.stdout"
      ignore_errors: true

    - name: Buscar evidencia de archivos *.asb
      become: true
      find:
        path: "{{ gdmfsasb }}"
        patterns: "*.asb"
      register: evidencia_asb

    - name: Borrar evidencias .asb
      become: true
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ evidencia_asb.files }}"      