---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- name: Obtener salidas de evidencias previas y posteriores al IPL de servicios, discos y salud del OS Linux
  block:
    - shell: cat {{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_previa.txt
      register: sso_pp_aps_total_pre

    - shell: cat {{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_intermedia.txt
      register: sso_pp_aps_total_inter

    - shell: cat {{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_posterior.txt
      register: sso_pp_aps_total_post

    - shell: cat {{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_diferencias.txt
      register: sso_pp_aps_total_dif

    - set_fact:
        ssoppapspre: "{{ sso_pp_aps_total_pre.stdout_lines }}"
        ssoppapsinter: "{{ sso_pp_aps_total_inter.stdout_lines }}"
        ssoppapspost: "{{ sso_pp_aps_total_post.stdout_lines }}"
        ssoppapsdif: "{{ sso_pp_aps_total_dif.stdout_lines }}"

- name: Almacenar evidencias previas y posteriores al IPL de servicios, discos y salud del OS Linux
  block:
    - copy:
        content: "{{ ssoppapspre | join('\n') }}"
        dest: "{{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_previa.txt"

    - copy:
        content: "{{ ssoppapsinter | join('\n') }}"
        dest: "{{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_intermedia.txt"

    - copy:
        content: "{{ ssoppapspost | join('\n') }}"
        dest: "{{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_posterior.txt"

    - copy:
        content: "{{ ssoppapsdif | join('\n') }}"
        dest: "{{ gdmfsasb }}{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}_{{ hostvars[inventory_hostname].ipaddress }}_foto_sso_pp_aps_diferencias.txt"
  delegate_to: asitsmaop2.bvm.bluecare.kyndryl.net

- name: Empaquetando y envio de evidencias en archivo zip
  block:
    - name: Buscar archivos y borrar archivos zip
      find:
        paths: "{{ gdmfsasb }}"
        patterns: "*.zip"
      register: zip_files

    - file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ zip_files.files }}"
      when: zip_files.matched > 0

    - find:
        paths: "{{ gdmfsasb }}"
        patterns: "{{ idcrqincreq }}*"
      register: archivos_filtrados

    - archive:
        path: "{{ archivos_filtrados.files | map(attribute='path') | list }}"
        dest: "{{ gdmfsasb }}{{ idcrqincreq }}_totales.zip"
        format: zip
        mode: '0644'
      with_items: "{{ archivos_filtrados.files }}"

    - shell: ls {{ gdmfsasb }}{{ idcrqincreq }}*totales.zip
      register: listflzip

    - name: Envio de evidencias por CRQ, INC o REQ
      mail:
        host: "{{ smtp }}"
        port: "{{ smtpport }}"
        from: "{{ mailfrom }}"
        to: "{{ mail_to }}"
        subject: "Reportes GDM Linux Patching"
        body: "Se adjuntan todas las evidencias del {{ idcrqincreq }} de previas y posteriores al IPL"
        attach: "{{ listflzip.stdout_lines }}"
      register: valmail
      no_log: true
  rescue:    
    - name: Envio de evidencias por folio CRQ, INC o REQ
      mail:
        host: "{{ smtp }}"
        port: "{{ smtpport }}"
        from: "{{ mailfrom }}"
        to: "gabriela.aranda.perez@company-xz.net"
        subject: "Reportes GDM Linux Patching"
        body: "Se adjuntan todas las evidencias del {{ idcrqincreq }} de previas y posteriores al IPL"
        attach: "{{ listflzip.stdout_lines }}"
      register: valmail
  always:
    - name: Envio de evidencias por folio CRQ, INC o REQ
      debug:
        msg: "{{ 'Se envio el correo al buzon o buzones:' + mail_to if mail_to != '' else 'Se envia el corre al buzon funional gabriela.aranda.perez.contractor@company-xz.net' }}"
      ignore_errors: true
  delegate_to: asitsmaop2.bvm.bluecare.kyndryl.net
  run_once: true